[package]
name = "learn_rust"
version = "0.1.1"
authors = ["xiongchenyu <xiongchenyu@bigo.sg>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
